include:
  - ../kafka/docker-compose.yaml
  - ../mongo/docker-compose.yaml

services:
  app:
    build:
      context: ../nestjs-api/.
      dockerfile: Dockerfile
    env_file:
      - ../nestjs-api/.env
    environment:
      - DATABASE_URL=mongodb://root:root@mongo:27017/nest?authSource=admin&directConnection=true
    networks:
      - backend_network
      - mongo_network
      - kafka_network
    ports:
      - 3001:3001
    depends_on:
      - mongo
    restart: unless-stopped
    deploy:
      mode: replicated
      replicas: 1

networks:
  backend_network:
    name: backend_network
    driver: bridge
  mongo_network:
    external: true
  kafka_network:
    external: true
