services:
  db:
    build: ./.docker/mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    networks:
      - mongo
    ports:
      - 27017:27017
    volumes:
      - ./mongodb_data:/data/db
    restart: unless-stopped

  app:
    build:
      context: ../nestjs-api/.
    env_file:
      - ../nestjs-api/.env
    environment:
      - DATABASE_URL=mongodb://root:root@db:27017/nest?authSource=admin&directConnection=true
    networks:
      - backend
      - mongo
    ports:
      - 3001:3001
    restart: unless-stopped
    deploy:
      mode: replicated
      replicas: 1

volumes:
  mongodb_data:
    driver: local

networks:
  backend:
    name: backend_network
    driver: bridge
  mongo:
    name: mongo_network
    driver: bridge